### ISSUE TITLE
After successful initial run, unable to setup

### ISSUE THREAD

**Issue by carn1x** [dzwicker/docker-youtrack#5]
My directory tree looks like:

```
.
├── docker-compose.yml
├── tmp
├── usr
│   └── local
│       └── youtrack
│           └── conf
└── var
    ├── lib
    │   └── youtrack
    └── log
        └── youtrack
```

And my docker-compose.yml looks like:

```
youtrack:
  image: dzwicker/docker-youtrack
  ports:
   - 8080:8080
  volumes:
   - ./var/lib/youtrack:/var/lib/youtrack
   - ./var/log/youtrack:/var/log/youtrack
   - ./usr/local/youtrack/conf:/usr/local/youtrack/conf
   - ./tmp:/tmp
  container_name: youtrack
```

`tmp/`, `usr/`, and `var/` are owned by 2000:2000 recursively.

I run the container with `docker-compose up -d`

It boots fine and allows me to register a user, however after registration the user account I just created is not recognized. My concern is whether there is some data persistence I'm unaware of, or if docker-compose is bringing it's own issues. If I remove all mention of `volumes` from `docker-compose.yml` then it loads fine and I can register and login, however I lose persistence.

As a side note, I'm also wondering if there should be more locations to be exposed as shared volumes, for instance to back up data from the built-in hub?

Thanks
